#!/system/bin/sh

# 加载profile.d下的所有sh配置
for i in $PREFIX/etc/profile.d/*.sh; do
  if [ -r $i ]; then
    . $i
  fi
done
unset i

# 加载bash配置
if [ "$(basename $0)" = "bash" ]; then
    BASH=true
    SHELL=$0
fi

if [ "$BASH" ]; then
  if [[ "$-" = *"i"* ]]; then
    if [ -r $PREFIX/etc/bash.bashrc ]; then
        . $PREFIX/etc/bash.bashrc
    fi
    if [ -r $HOME/.bashrc ]; then
        . $HOME/.bashrc
    fi
  fi
fi
